version: "3.4"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.39
    ports:
      - 16686:16686
      - 14250
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - 55680:55680
      - 9411:9411
    depends_on:
      - jaeger
